### PR TITLE
Update hfc protos

### PR DESCRIPTION
**Pull request by Kelvin-M**
To prepare the compatibility with Hyperledger 2.x
Update hfc protos to latest version from https://github.com/hyperledger/fabric-protos.

### CODE REVIEW

**Review by dexhunter — DISMISSED** [review]
lgtm

**Comment by yeasy** [comment]
@Kelvin-M just to confirm the proto files are from Fabric v1.4.x version?

**Comment by Kelvin-M** [comment]
@yeasy Those proto files are from https://github.com/hyperledger/fabric-protos (master). As there is no version tagged, I don't know if there is any compatibility issue between proto files for Fabric v1.4.x and Fabric 2.x. 
Those proto files look like compatible for Fabric 2.x (as they include new chaincode lifecycle) but unit tests show that it works for v1.4.x too.
Do you have any idea if this is an issue ?

**Comment by yeasy** [comment]
> @yeasy Those proto files are from https://github.com/hyperledger/fabric-protos (master). As there is no version tagged, I don't know if there is any compatibility issue between proto files for Fabric v1.4.x and Fabric 2.x.
> Those proto files look like compatible for Fabric 2.x (as they include new chaincode lifecycle) but unit tests show that it works for v1.4.x too.
> Do you have any idea if this is an issue ?

OK, we will cut a `release-1.0` branch to track improving HLF v1.x support after #118 and #119 .
How about we merge this patchset after the new branch created.

@dexhunter @Kelvin-M

**Review by yeasy — APPROVED** [review]

**Comment by yeasy** [comment]
HLF v1.4 features will be tracked at https://github.com/hyperledger/fabric-sdk-py/tree/release-1.0.

**Pull request merged**
