### PR TITLE
This patch fixed syntax errors

### PR DESCRIPTION
**Pull request by litong01**

### CODE REVIEW

**Comment by dexhunter** [comment]
However, it seems that this piece of code is not coveraged at unit-test, maybe we should consider how to include it?

**Comment by litong01** [comment]
this is currently broken. need this fix asap. I believe there are so many other code not being tested, otherwise, this syntax error would have never passed.

**Comment by GuillaumeCisco** [comment]
I express my warning about this modification.
I think this piece of code will break the existing.
I will do more tests about this part.

**Comment by litong01** [comment]
@GuillaumeCisco why would it break the existing? the code as is never worked in python 3. Can you provide a bit reason for your concern? Also, the x['evts'] accesses the member never exists, it should have gotten x[_uuid]['evts']. Which I have tested in my env. The reason I found this error is because it throw the exceptions in my test env. with the fixes, things started working. please update here so that we get things right. Also like to see your test results.

**Comment by GuillaumeCisco** [comment]
Thanks @litong01,
I just made more tests. Indeed this piece of code was not tested.
Your fix is good.
However, I wonder how did you manage to get multiple `events` with the same chaincode registration.

```python
x[_uuid]['evts'] += [evt]
break
```
should never be reached from my understanding as chaincode methods can only send one event.

I understood you ran into the `_uuid = x.keys()[0]` error, thanks again for fixing it.

I will add a PR which test this part of the code ;)

**Comment by litong01** [comment]
@GuillaumeCisco the original code was 
`
x['evts'] += [evt]
'

which throws exceptions, due to access the none existing member, the fixed just added x[_uuid] so that there is no exception thrown, in terms of multiple events, I assume that the original x[_uuid]['evts'] may have been initialized as empty.

**Comment by GuillaumeCisco** [comment]
How did you manage to have multiple events and induce this error?

**Pull request merged**
