### PR TITLE
prune deprecated peer event port 7053

### PR DESCRIPTION
**Pull request by davidkhala**
code hygience
Signed-off-by: DavidLiu <david.yx.liu@oracle.com>

### CODE REVIEW

**Comment by yeasy** [comment]
CI is not happy!

**Comment by davidkhala** [comment]
> CI is not happy!

Noted and it seems interesting.

**Comment by dexhunter** [comment]
I've re-runned the test, the error seems to be caused by async problem

**Review by dexhunter — APPROVED** [review]
lgtm

**Pull request merged**
