### PR TITLE
Added pem processing for connection profile

### PR DESCRIPTION
**Pull request by dpdornseifer**
As discussed in ( https://jira.hyperledger.org/browse/FABN-808?focusedCommentId=42160&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-42160 )
is comes handy if the SDK can be fully parameterized using the config profile, in particular for debugging and testing purpose.

To avoid further issues (encoding, format, ...) with the 'pem' contents, the certs and keys should be base64 encoded.

Signed-off-by: David <dornseid@amazon.com>

### CODE REVIEW

**Comment by dpdornseifer** [comment]
@yeasy @dexhunter this is a feature request that comes very handy and is supported by other SDKs like go(lang). Whats your opinion about this? To get it merged changes in the documentation are still required.

**Comment by dexhunter** [comment]
@dpdornseifer Hi, David. Yes, I think the feature is quite and we should support it at the Python SDK

**Comment by dpdornseifer** [comment]
@dexhunter @yeasy @dongwangdw @GuillaumeCisco can you please review

**Review by yeasy — APPROVED** [review]

**Comment by dpdornseifer** [comment]
@yeasy thx for approving - think we have to look into the make docs section in the pipeline - the `tutorial.html` section has not been updated yet.

**Pull request merged**
