### PR TITLE
fixed chaincode upgrade, added tests for chaincode upgrade

### PR DESCRIPTION
**Pull request by nkalichynskyi**
fixed chaincode upgrade, added tests for chaincode upgrade, refactoring

Signed-off-by: nkalichynskyi <ext-nazarii.kalichynskyi@here.com>

### CODE REVIEW

**Comment by nkalichynskyi** [comment]
@dexhunter @yeasy, please advise how to proceed with this issue, I've tried disabling the check for a specific line, but it doesn't have any effect.

**Comment by dexhunter** [comment]
@nkalichynskyi Hi! I think just comment `# noqa` is fine.

**Review by dexhunter — APPROVED** [review]
lgtm

**Comment by nkalichynskyi** [comment]
I've added both `# noqa F401` and `# lgtm[py/unused-import]`, noqa comment works fine, and flake8 check passes, but check on lgtm.com still fails.

**Comment by dexhunter** [comment]
> I've added both `# noqa F401` and `# lgtm[py/unused-import]`, noqa comment works fine, and flake8 check passes, but check on lgtm.com still fails.

it actually passed, only alerts, and there are some pre-existing alerts as well.

**Comment by nkalichynskyi** [comment]
ok, got it, thanks

**Pull request merged**
