### PR TITLE
Jupyter Notebook

### PR DESCRIPTION
**Pull request by RohanShrothrium**
Signed-off-by: rohanshrothrium <shrothriumrohan@gmail.com>

@dexhunter and @yeasy this is just a basic structure for creating a channel.
Give me a feedback regarding the same so I can continue to do the same for other parts of the tutorial.

### CODE REVIEW

**Comment by dexhunter** [comment]
@RohanShrothrium Also please include the setup instruction here. It will save the time for new developers.

**Comment by RohanShrothrium** [comment]
> I checked the [preview](https://github.com/RohanShrothrium/fabric-sdk-py/blob/JupyterNotebook/Tutorial.ipynb). Please put the file under `docs` and give pointer at the documentations, besides please give the results of the execution.

The code doesn't run as expected as the Jupyter notebook will be running from `/docs` and not from the root directory. So I'll have to make a few changes in the `network.json` file. So I have left the notebook at the root directory itself.

I have also included the setup in this itself.

**Comment by dexhunter** [comment]
You need to properly import the library. But we can leave it at the root
directory for now

**Comment by dexhunter** [comment]
@RohanShrothrium Hi, could you have a look at CI error. You can exclude `.ipynb` from `tox.in` check list.

**Comment by RohanShrothrium** [comment]
> The jupyter notebook is good.
> And we need a sample code to demo all existing APIs ASAP.

Will work on that this week!

**Pull request merged**
