### PR TITLE
added project project_urls property to setup.py to comply with OSS andards

### PR DESCRIPTION
**Pull request by nkalichynskyi**
Signed-off-by: nkalichynskyi <ext-nazarii.kalichynskyi@here.com>

### CODE REVIEW

**Comment by nkalichynskyi** [comment]
@dexhunter, can you please check what's wrong with this pipeline it doesn't seem to be running

**Review by yeasy — APPROVED** [review]

**Comment by nkalichynskyi** [comment]
@yeasy @dexhunter, can you please check what's up with this PR's pipeline, or maybe it can be merged without tests since there was no change to the codebase?

**Review by dexhunter — APPROVED** [review]
lgtm

**Pull request merged**
