### PR TITLE
[FAB-18266] replaced hardcoded CC_TYPE_GOLANG with parameters

### PR DESCRIPTION
**Pull request by Colin-1-Smith-here-com**
Also added NODE support to the tar package creation

Signed-off-by: Colin-1-Smith-here-com <Colin.1.Smith@here.com>

### CODE REVIEW

**Comment by yeasy** [comment]
Seems pylint failed, please check the result at https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=23321&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&l=4814.
Thanks!

**Review by dexhunter — APPROVED** [review]
lgtm

**Comment by Colin-1-Smith-here-com** [comment]
> Seems pylint failed, please check the result at https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=23321&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&l=4814.
> Thanks!

I can't replicate this locally. I'm getting:

`
======================= 128 passed in 557.09s (0:09:17) ========================
___________________________________ summary ____________________________________
  pylint: commands succeeded
  congratulations :)
...
___________________________________ summary ____________________________________
  flake8: commands succeeded
  congratulations :)

...

============================================ 128 passed in 563.79s (0:09:23) ============================================
________________________________________________________ summary ________________________________________________________
  py36: commands succeeded
  congratulations :)
`

**Comment by yeasy** [comment]
> > Seems pylint failed, please check the result at https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=23321&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&l=4814.
> > Thanks!
> 
> I can't replicate this locally. I'm getting:
> 
> `
> ======================= 128 passed in 557.09s (0:09:17) ========================
> ___________________________________ summary ____________________________________
> pylint: commands succeeded
> congratulations :)
> ...
> ___________________________________ summary ____________________________________
> flake8: commands succeeded
> congratulations :)
> 
> ...
> 
> ============================================ 128 passed in 563.79s (0:09:23) ============================================
> ________________________________________________________ summary ________________________________________________________
> py36: commands succeeded
> congratulations :)
> `

@Colin-1-Smith-here-com can you run `make check` locally (i'm using ubuntu 20.04)?
I run it twice and got errors as the following:

.....

=========================================================================================================================== short test summary info ============================================================================================================================
FAILED test/integration/discovery_test.py::DiscoveryTest::test_discovery - IndexError: list index (0) out of range
FAILED test/integration/e2e_mutual_tls_test.py::E2eMutualTest::test_in_sequence - TypeError: string indices must be integers
FAILED test/integration/e2e_private_data_test.py::E2ePrivateDataTest::test_in_sequence - TypeError: string indices must be integers
FAILED test/integration/e2e_test.py::E2eTest::test_in_sequence - TypeError: string indices must be integers
FAILED test/integration/query_block_test.py::QueryBlockTest::test_query_block_by_hash_encoded - TimeoutError: waitForEvent timed out.
FAILED test/integration/query_block_test.py::QueryBlockTest::test_query_block_by_hash_success - TimeoutError: waitForEvent timed out.
FAILED test/integration/query_block_test.py::QueryBlockTest::test_query_block_encoded - TimeoutError: waitForEvent timed out.
FAILED test/integration/query_block_test.py::QueryBlockTest::test_query_block_success - TimeoutError: waitForEvent timed out.
FAILED test/integration/query_chain_info_test.py::QueryChainInfoTest::test_query_chain_info - TimeoutError: waitForEvent timed out.
FAILED test/integration/query_instantiated_chaincodes_test.py::ChaincodeInvokeTest::test_query_instantiated_chaincodes_success - grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
FAILED test/integration/query_transaction_test.py::QueryTransactionTest::test_query_transaction_id_encoded - TimeoutError: waitForEvent timed out.
FAILED test/integration/query_transaction_test.py::QueryTransactionTest::test_query_transaction_id_success - grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
================================================================================================================= 12 failed, 116 passed in 1094.43s (0:18:14) ==================================================================================================================
ERROR: InvocationError for command /home/test/fabric-sdk-py/.tox/pylint/bin/py.test --cov=hfc test -s (exited with code 1)
___________________________________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________________________________
ERROR:   pylint: commands failed
make[2]: *** [Makefile:26: tox.pylint] Error 1
make[2]: Leaving directory '/home/test/fabric-sdk-py'
make[1]: *** [Makefile:22: test] Error 2
make[1]: Leaving directory '/home/test/fabric-sdk-py'
make: *** [Makefile:12: check] Error 2

**Comment by Colin-1-Smith-here-com** [comment]
ok I was having problems replicating these errors, but I'm seeing them intermittently now as well.
Not every run. I can attach a log if necessary. 

I decided to run make check in a loop on the master and FAB-18266 branches.
0 represents success, 1 represents failure.

On master branch
$ ./runcheck.sh 
0
1
1
1
0
1
0
0
1

$ git checkout FAB-18266
Switched to branch 'FAB-18266'
Your branch is up to date with 'origin/FAB-18266'.
~/git/github.com/Colin-1-Smith-here-com/fabric-sdk-py:
$ ./runcheck.sh
1
0
1
1
0
0
1
1
0

It looks like a race condition, or, a build / download timeout is involved.

**Comment by Colin-1-Smith-here-com** [comment]
I've done some investigating into what is going on within the tests when they fail on the master branch.
The one which was failing most was the discovery_test.py check. 

The example_cc chaincode gets installed fine on both of the peers, but it fails to instantiate. Here's the network state at point of failure.
```
$ docker ps
CONTAINER ID        IMAGE                                                                                                        COMMAND                  CREATED             STATUS              PORTS                                                                                                NAMES
11828ac14366        dev-peer0.org1.example.com-example_cc-1.0-10d7c1ee74b2c7dae68a5159a982d3d45bd8100ad144168f674fbde09a57ef8a   "chaincode -peer.add…"   16 hours ago        Up 16 hours                                                                                                              dev-peer0.org1.example.com-example_cc-1.0
4b9095446203        hyperledger/fabric-peer:1.4.6                                                                                "peer node start"        16 hours ago        Up 16 hours         7050/tcp, 7054-7059/tcp, 0.0.0.0:7051-7053->7051-7053/tcp                                            peer0.org1.example.com
f1178ed63858        hyperledger/fabric-peer:1.4.6                                                                                "peer node start"        16 hours ago        Up 16 hours         7050/tcp, 7054-7059/tcp, 0.0.0.0:8051->7051/tcp, 0.0.0.0:8052->7052/tcp, 0.0.0.0:8053->7053/tcp      peer1.org1.example.com
48b3cbf649c9        hyperledger/fabric-orderer:1.4.6                                                                             "orderer start"          16 hours ago        Up 16 hours         0.0.0.0:7050->7050/tcp                                                                               orderer.example.com
bc29a5f78f05        hyperledger/fabric-peer:1.4.6                                                                                "peer node start"        16 hours ago        Up 16 hours         7050/tcp, 7054-7059/tcp, 0.0.0.0:10051->7051/tcp, 0.0.0.0:10052->7052/tcp, 0.0.0.0:10053->7053/tcp   peer1.org2.example.com
dca8fc6162b3        hyperledger/fabric-peer:1.4.6                                                                                "peer node start"        16 hours ago        Up 16 hours         7050/tcp, 7054-7059/tcp, 0.0.0.0:9051->7051/tcp, 0.0.0.0:9052->7052/tcp, 0.0.0.0:9053->7053/tcp      peer0.org2.example.com
```
Peer 0 has the chaincode container up and connected. Peer 1 doesn't. It isn't simply a timeout problem either, e.g. slow package downloads. Peer1 never recovers and starts the chaincode. Doesn't matter if you set the delays in the test to 60, 120 seconds, it remains stuck.

I haven't managed to get into the container while it's building, but I can see from the container logs that peer1 never makes it to the container Launch stage

peer0 log:
```
[36m2020-10-27 16:20:36.262 UTC [chaincode] LaunchConfig -> DEBU 285[0m launchConfig: executable:"chaincode",Args:[chaincode,-peer.address=peer0.org1.example.com:7052],Envs:[CORE_CHAINCODE_LOGGING_LEVEL=info,CORE_CHAINCODE_LOGGING_SHIM=warning,CORE_CHAINCODE_LOGGING_FORMAT=%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message},CORE_CHAINCODE_ID_NAME=example_cc:1.0,CORE_PEER_TLS_ENABLED=true,CORE_TLS_CLIENT_KEY_PATH=/etc/hyperledger/fabric/client.key,CORE_TLS_CLIENT_CERT_PATH=/etc/hyperledger/fabric/client.crt,CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/peer.crt],Files:[/etc/hyperledger/fabric/client.crt /etc/hyperledger/fabric/client.key /etc/hyperledger/fabric/peer.crt]
[36m2020-10-27 16:20:36.262 UTC [chaincode] Start -> DEBU 286[0m start container: example_cc:1.0
[36m2020-10-27 16:20:36.262 UTC [chaincode] Start -> DEBU 287[0m start container with args: chaincode -peer.address=peer0.org1.example.com:7052
[36m2020-10-27 16:20:36.262 UTC [chaincode] Start -> DEBU 288[0m start container with env:
	CORE_CHAINCODE_LOGGING_LEVEL=info
	CORE_CHAINCODE_LOGGING_SHIM=warning
	CORE_CHAINCODE_LOGGING_FORMAT=%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}
	CORE_CHAINCODE_ID_NAME=example_cc:1.0
	CORE_PEER_TLS_ENABLED=true
	CORE_TLS_CLIENT_KEY_PATH=/etc/hyperledger/fabric/client.key
	CORE_TLS_CLIENT_CERT_PATH=/etc/hyperledger/fabric/client.crt
	CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/peer.crt

.... log snipped ....
[36m2020-10-27 16:20:37.784 UTC [dockercontroller] Start -> DEBU 29c[0m Started container dev-peer0.org1.example.com-example_cc-1.0
.... log snipped ....
[36m2020-10-27 16:20:37.797 UTC [chaincode] Launch -> DEBU 2a9[0m launch complete
```

On peer1. It never gets there. No launch for example_cc. There are launches for the internal chaincodes; lscc, qscc etc.
The example_cc chaincode is installed peer1 though:

```
[34m2020-10-27 16:20:36.253 UTC [lscc] executeInstall -> INFO 25a[0m Installed Chaincode [example_cc] Version [1.0] to peer
```

The problem seems to be in between install and instantiate. I kind of suspect that it is a network problem downloading packages while go is building the chaincode on the peer. I can't find any details in the peer0 or peer1 log though about the build process, to indicate what's going on at the time. And if it is the problem, I'm not sure if it's fixable other than more bandwidth because it's building in a subcontainer which is managed by the peer. A caching proxy container maybe.

**Comment by yeasy** [comment]
@dexhunter can you check the discovery_test.py to see why peer1 cannot instantiate the chaincode?

**Comment by dexhunter** [comment]
@Colin-1-Smith-here-com Hi, could you rebase to the latest commit of master branch? Thank you!

**Review by dexhunter — APPROVED** [review]
lgtm

**Comment by nkalichynskyi** [comment]
@dexhunter can you please review this PR again?

**Review by dexhunter — APPROVED** [review]
lgtm

**Comment by dexhunter** [comment]
@nkalichynskyi sorry for the late reply.

**Pull request merged**
