### PR TITLE
Jupyter notebook

### PR DESCRIPTION
**Pull request by RohanShrothrium**

### CODE REVIEW

**Review by dexhunter — APPROVED** [review]

**Comment by dexhunter** [comment]
@RohanShrothrium please rebase the code to the latest commit

**Comment by RohanShrothrium** [comment]
> @RohanShrothrium please rebase the code to the latest commit of the master branch

I rebased and pushed

**Comment by dexhunter** [comment]
Hmm...why there is so many changes, which version did you rebase to?

**Comment by RohanShrothrium** [comment]
I'm closing this PR and opening from a separate branch!

**Pull request closed without merging**
