### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by viragumathe5**
Updates for virtualenv, and intro and other

### CODE REVIEW

**Comment by viragumathe5** [comment]
@dexhunter I think I messed up everything in my pull request should I start again???

**Comment by dexhunter** [comment]
> @dexhunter I think I messed up everything in my pull request should I start again???

Sure, you can close this PR.

**Comment by viragumathe5** [comment]
@dexhunter yeah I was thinking while looking the master that where is that Build folder thank you for the comment I will change index.md now ok and I want to contribute to making a guide for new contributors also like a **Making contributions to Fabric-sdk-py** do you think will it be helpful???

Right now CONTRIBUTING.md is also empty so I am on it

**Comment by dexhunter** [comment]
@viragumathe5 `CONTRIBUTING.md` is not empty, it's just a pointer to another file. Please check [this one](https://github.com/hyperledger/fabric-sdk-py/blob/master/CONTRIBUTING.md)

**Comment by viragumathe5** [comment]
ohhh I am sorry

**Pull request closed without merging**
