### PR TITLE
Adopt sphynx style for API documentation.

### PR DESCRIPTION
**Pull request by kmehant**
- [x] `hfc/fabric`
- [x] `hfc/utils`
- [x] `hfc/fabric_ca`
- [x] `hfc/fabric_network`
Signed-off-by: K mehant <411843@student.nitandhra.ac.in>

### CODE REVIEW

**Comment by kmehant** [comment]
@dexhunter 
As these are huge changes in terms of number of lines. I would request you to give a casual review on the work so far so that I can continue on the other parts.

**Comment by kmehant** [comment]
@dexhunter I have completed it, Please review!

**Comment by dexhunter** [comment]
Some flake8 errors need to be fixed

```
[31064] /home/vsts/work/1/s$ /home/vsts/work/1/s/.tox/flake8/bin/flake8 hfc test test --exclude=protos
hfc/fabric_ca/identityService.py:22:109: W291 trailing whitespace
hfc/fabric_ca/identityService.py:25:121: E501 line too long (131 > 120 characters)
hfc/fabric_ca/caservice.py:639:59: W291 trailing whitespace
hfc/fabric_ca/certificateService.py:32:121: E501 line too long (165 > 120 characters)
hfc/fabric/user.py:179:28: W291 trailing whitespace
hfc/fabric/channel/channel.py:199:28: W291 trailing whitespace
hfc/fabric/channel/channel.py:215:28: W291 trailing whitespace
hfc/fabric/channel/channel.py:236:28: W291 trailing whitespace
hfc/fabric/channel/channel.py:1091:25: W291 trailing whitespace
hfc/util/utils.py:307:31: W291 trailing whitespace
hfc/util/utils.py:323:30: W291 trailing whitespace
hfc/fabric_network/inmemorywalletstore.py:20:31: W291 trailing whitespace
hfc/fabric_network/wallet.py:81:23: W291 trailing whitespace
ERROR: InvocationError for command /home/vsts/work/1/s/.tox/flake8/bin/flake8 hfc test test --exclude=protos (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   flake8: commands failed
```

**Comment by kmehant** [comment]
@dexhunter Fixed :)

**Comment by dexhunter** [comment]
Thanks for your contribution! @kmehant

**Pull request merged**
