### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by viragumathe5**
Documentation cleanup and linked.

### CODE REVIEW

**Comment by viragumathe5** [comment]
@dexhunter according to your suggestion and discussion I am on API documentation but I just made this last change would you please review this 

In the index page, only links are provided for the easy navigation now I have created files for each link once it gets published I will change it to the web links.

Secondary I am API documentation and will complete it very soon

Thank You

**Comment by ryjones** [comment]
please rebase to the tip of master

**Comment by viragumathe5** [comment]
Oh I am so sorry @dexhunter I really had a misunderstanding I am sorry for that this won't happen again 
I am sorry so should I close this PR ???

**Comment by dexhunter** [comment]
@viragumathe5 No problem, please do check the source code and add explanations if you are able to. Thank you!

**Comment by viragumathe5** [comment]
Yes definitely @dexhunter

**Pull request closed without merging**
