### PR TITLE
Typo in variable name: orgq_admin --> org1_admin

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Review by dexhunter — APPROVED** [review]
lgtm

**Comment by cclauss** [comment]
Guys, what is the purpose of a DCO?  Is it a developer’s certificate of originality?  How much originality do you expect to find in fixing a typo?  I doubt that it is an original idea to delete a q and insert a 1.

**Comment by dexhunter** [comment]
@cclauss Hi, actually you only need to sign the commit as indicated [here](https://github.com/hyperledger/fabric-sdk-py/pull/109/checks?check_run_id=1019303390) and it will pass. Also please rebase to the latest commit. Thanks.

**Comment by yeasy** [comment]
> Guys, what is the purpose of a DCO? Is it a developer’s certificate of originality? How much originality do you expect to find in fixing a typo? I doubt that it is an original idea to delete a q and insert a 1.

Hi, cclauss, the purpose of DCO is not for originality only, but more like a commitment that the patch will follow the Apache v2 license, which is required by every Hyperledger open source project.

Here are more details: https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for.

Thanks!

**Comment by dexhunter** [comment]
fixed in #147

**Pull request closed without merging**
