### PR TITLE
added osn admin module

### PR DESCRIPTION
**Pull request by nkalichynskyi**
In the new fabric release, it's mentioned that the system channel approach to managing orderers will be deprecated so it might be useful to have osn admin in the SDK so the network can be managed with one tool.

### CODE REVIEW

**Review by dexhunter — APPROVED** [review]
lgtm

**Comment by yeasy** [comment]
=========================== short test summary info ============================
FAILED test/integration/e2e_test.py::E2eTest::test_in_sequence - AssertionErr...
================== 1 failed, 130 passed in 739.43s (0:12:19) ===================
ERROR: InvocationError for command /home/vsts/work/1/s/.tox/pylint/bin/py.test --cov=hfc test -s (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   pylint: commands failed
Makefile:25: recipe for target 'tox.pylint' failed
make[2]: Leaving directory '/home/vsts/work/1/s'
make[2]: *** [tox.pylint] Error 1
Makefile:22: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/home/vsts/work/1/s'
Makefile:10: recipe for target 'check' failed
make: *** [check] Error 2
##[error]Bash exited with code '2'.

**Comment by nkalichynskyi** [comment]
I've updated a bit `make check` command to run tests only once because previously it was running them for both `pylint` and `py36` stages, but It's still failing randomly.

**Comment by yeasy** [comment]
/azp run

Will re-trigger, and thanks!

**Review by yeasy — APPROVED** [review]

**Pull request merged**
