### PR TITLE
Update docker-compose version for requests compatibility

### PR DESCRIPTION
**Pull request by Kelvin-M**

### CODE REVIEW

**Comment by dexhunter** [comment]
I think this needs to be rebased to pass the CI. (it uses the outdated url to download fabric-bins)

**Comment by Kelvin-M** [comment]
@dexhunter Yes, but we need to rebase https://github.com/hyperledger/fabric-sdk-py/pull/12 as I do my branch to complete this PR, have you the rights to rebase https://github.com/hyperledger/fabric-sdk-py/pull/12 ?

**Comment by dexhunter** [comment]
I just asked the bot to rebase the branch. Let see if the test passes now

**Comment by dexhunter** [comment]
Besides, does @GuillaumeCisco approve this change?

**Comment by dexhunter** [comment]
I still have no idea why it always fails at first build. Is it caused by network or something else?

**Pull request closed without merging**
